version: "3.7"
services:
#  nginx:
#   build: 
#    context: ./requirements/nginx
#    args:
#     BUILD_DATE: Sun May 29 19:32:06 +01 2022
#   image: nginx:${TAG}
#   container_name: nginx
#   ports:
#    - "443:443"
#   env_file:
#    - .env
 mariadb:
    image: mariadb:${TAG}
    container_name: maria
    build:
     context: ./requirements/mariadb/
     args:
      BUILD_DATE: Sun May 29 19:32:06 +01 2022
    # networks:
    #   - inception_network
    # volumes:
    #   - maria_vol:/var/lib/mysql
    env_file:
      - .env
#  wordpress:
#   image: wordpress:${TAG}
#   container_name: wp
#   depends_on:
#    - mariadb
#   networks:
#    - inception_network
#   env_file:
#    - .env
#   build:
#    context: ./requirements/wordpress
#    args:
#     BUILD_DATE: Sun May 29 19:32:06 +01 2022
#   ports:
#    - '9000:9000'
#   volumes:
#    - wordpress_vol:/var/www/html/wordpress
#   restart: always

networks:
  inception_network:
    driver: bridge

volumes:
 wordpress_vol:
  driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/aybouras/Desktop/inception_volumes/wordpress'
 maria_vol:
  driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/aybouras/Desktop/inception_volumes/maria'
