version: "3.7"
services:
 nginx:
  build: 
   context: ./requirements/nginx
   args:
    BUILD_DATE: Tue May 24 16:08:33 +01 2022
  image: nginx
  ports:
   - "443:443"
  env_file:
   - .env
 wordpress:
  image: wordpress
  depends_on:
   - mariadb
  networks:
   - inception_net
  env_file: .env
  build:
   context: ./requirements/wordpress
#   ports:
#    - '9000:9000'
  volumes:
   - wordpress_vol:/var/www/html
  container_name: wordpress
  restart: always