version: "3.7"
services:
 nginx:
  build: 
   context: ./requirements/nginx
   args:
    BUILD_DATE: Sun Jun  5 21:02:57 +01 2022
  image: nginx:${TAG}
  container_name: nginx
  ports:
   - "443:443"
   - "8080:8080"
  env_file:
   - .env
  volumes:
   - wordpress_vol:/var/www/wordpress
   - adminer_vol:/var/www/adminer
  networks:
    - inception_network
  restart: always

 mariadb:
    image: mariadb:${TAG}
    container_name: mariadb
    build:
     context: ./requirements/mariadb/
     args:
      BUILD_DATE: Sun Jun  5 21:02:57 +01 2022
    networks:
      - inception_network
    ports:
      - 3306:3306
    volumes:
      - maria_vol:/var/lib/mysql
    env_file:
      - .env
    restart: always

 wordpress:
  image: wordpress:${TAG}
  container_name: wordpress
  depends_on:
   - mariadb
   - nginx
  networks:
   - inception_network
  env_file:
   - .env
  build:
   context: ./requirements/wordpress
   args:
    BUILD_DATE: Sun Jun  5 21:02:57 +01 2022
  expose:
   - 9000
  volumes:
   - wordpress_vol:/var/www/wordpress
  restart: always

 redis:
  build: ./requirements/bonus/redis
  image: redis:${TAG}
  container_name: redis
  depends_on:
   - wordpress
  networks:
    - inception_network
  expose:
  - 6379
  restart: always
  volumes:
   - wordpress_vol:/var/www/wordpress

#  ftp:
#   image: ftp
#   env_file: .env
#   build:
#       context: ./requirements/bonus/ftp
#   depends_on:
#      - wordpress
#   container_name: ftp
#   ports:
#       - '21:21'
#       - '20:20'
#   volumes:
#       - wordpress_vol:/Users/aybouras/Desktop/inception_git/
#   networks:
#       - inception_network
#   restart: always 
 
 adminer:
  build: ./requirements/bonus/adminer
  image: adminer:${TAG}
  container_name: adminer
  expose:
    - 7000
  networks:
    - inception_network
  restart: always
  depends_on:
  # - wordpress
  - nginx
  volumes:
   - adminer_vol:/var/www/adminer
  
networks:
  inception_network:
    driver: bridge

volumes:
 wordpress_vol:
  driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/aybouras/Desktop/inception/wordpress_vol'
 maria_vol:
  driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/aybouras/Desktop/inception/maria_vol'
 adminer_vol:
  driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/aybouras/Desktop/inception/adminer_vol'
