version: "3.7"
services:
#  
 wordpress:
  image: wordpress:${TAG}
  container_name: wp
  # depends_on:
  #  - mariadb
  networks:
   - inception_network
  env_file:
   - .env
  build:
   context: ./requirements/wordpress
   args:
    BUILD_DATE: Sat May 28 14:48:21 +01 2022
  ports:
   - '9000:9000'
  volumes:
   - wordpress_vol:/var/www/html/wordpress
  restart: always

networks:
  inception_network:
    driver: bridge

volumes:
 wordpress_vol:
  driver_opts:
    type: 'none'
    o: 'bind'
    device: '/Users/aybouras/Desktop/inception_volumes/wordpress'
#  maria_vol:
#   driver_opts:
#     type: 'none'
#     o: 'bind'
#     device: '/Users/aybouras/Desktop/inception_volumes/maria'
